import type { Metadata } from "next";
import 'bootstrap/dist/css/bootstrap.min.css';
import localFont from 'next/font/local';
import "./globals.css";

import NavbarTop from "@/components/Navbar/NavbarTop";
import NavbarMain from "@/components/Navbar/NavbarMain";
import FooterMain from "@/components/Footer/FooterMain";
import FooterButtom from "@/components/Footer/FooterButtom";

const myArabicFont = localFont({
  src: './fonts/JF-Flat-regular.ttf', 
  variable: '--font-arabic',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl" data-scroll-behavior='smooth'>
      <body className={myArabicFont.className}>
        <NavbarTop/>
        <NavbarMain/>
        <main className='min-vh-100'>
          {children}
        </main>
        <FooterMain/>
        <FooterButtom/>
      </body>
    </html>
  );
}
